---
name: security-scan-sast

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 4'  # Runs at 04:30, only on Thursday - update this schedule

jobs:
  scan:
    uses: ./.github/workflows/semgrep.yaml
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
